# Test Tool Classify Text

_Last Update:_ 2026-02-06

The goal of this notebook is to create tests that ensure that the tool and its associated functions work as intended. Going from functional coding to actual performance.

## Environment Settings

In [1]:
import os
import sys
from pathlib import Path
import warnings
import pandas as pd
warnings.filterwarnings("ignore")

# PROJECT ROOT to Python paths
ROOT_DIR = Path().resolve().parents[0]
if str(ROOT_DIR) not in sys.path:
    sys.path.insert(0, str(ROOT_DIR))
# RELOAD the custom script
%load_ext autoreload
%autoreload 2

In [2]:
from dotenv import load_dotenv
# Load environment variables from .env file
SECRETS_FILE = Path(r"C:\LocalSecrets\master.env")
load_dotenv(str(SECRETS_FILE))
# ASSIGN the values of the environment variables
openai_key = str(os.getenv("OPENAI_UIO24EMC_KEY"))

## S01 System Message and Prompt Constructors

This validation process is not about performace but computatinal functionality such that the prompts do exactly what is intended.

- `is_agent_target/*.py`

### Prompt Constructor `def prompt_is_agent_target()`

In [ ]:
# IMPORT the Prompt Function and the System Message
from gptquery.tools.tool_classify_text.is_sentence_valance.prompts.default import (prompt_is_sentence_valance, 
                                                                               IS_SENTENCE_SYSTEM_MESSAGE)

example_snippet = """Henry Schermers once said to me that, whereas German lawyers came to Community
law through constitutional law, and French lawyers came through international
law, British lawyers came to it through comparative law.
"""
example_entities = "Community law"

# PRINT System message and USER MESSAGE
print(IS_SENTENCE_SYSTEM_MESSAGE)
print("*"*100)
print(prompt_is_sentence_valance(snippet_text=example_snippet,entities_str=example_entities))

In [ ]:
# IMPORT the Prompt Function
from gptquery.tools.tool_classify_text.is_sentence_valance.prompts.default import prompt_is_sentence_valance

# LOAD cmlr_authors_sample
cmlr_snippets = pd.read_parquet(ROOT_DIR / "data/uot25rev/cmlr_snippets_sample.parquet")
# TEST Prompt constructing function
cmlr_snippets["validate_prompt"] = cmlr_snippets.apply(lambda row: prompt_is_sentence_valance(row["snippet_text"],
                                                                                        row["entities_str"]), axis=1)
cmlr_snippets.head(5)

,snippet_id,snippet_text,entities_str,validate_prompt
0,CMLR1963004_S001,"On the other hand, the continental approach, p...",the court,LIST OF RELEVANT ENTITIES:\nthe court\n\nTEXT ...
1,CMLR1963005_S035,As this declaration in the cases referred to i...,"the Commission,the Commission","LIST OF RELEVANT ENTITIES:\nthe Commission,the..."
2,CMLR1963006_S028,It is particularly unrealistic of the Commissi...,"the Commission,the Commission","LIST OF RELEVANT ENTITIES:\nthe Commission,the..."
3,CMLR1963014_S009,The Council acting on a proposal olC the Com...,the Commission,LIST OF RELEVANT ENTITIES:\nthe Commission\n\n...
4,CMLR1963014_S044,In cases where this Article applies the Commis...,the Commission,LIST OF RELEVANT ENTITIES:\nthe Commission\n\n...

## S02 Reliability Test

- `run_is_agent_target_basic()`

####  `run_is_agent_target_basic()` TEST

In [ ]:
from gptquery.tools.tool_classify_text import run_is_sentence_valance_basic
cmlr_snippets = pd.read_parquet(ROOT_DIR / "data/uot25rev/cmlr_snippets_sample.parquet")[:10]

is_agent_target_df  = run_is_sentence_valance_basic(cmlr_snippets, api_key=openai_key, 
                                                                model="gpt-4.1-mini")

is_agent_target_df

Starting run_is_agent_target of 10 rows using openai...
Progress: 1/10 (10.0%)
Progress: 2/10 (20.0%)
Progress: 3/10 (30.0%)
Progress: 4/10 (40.0%)
Progress: 5/10 (50.0%)
Progress: 6/10 (60.0%)
Progress: 7/10 (70.0%)
Progress: 8/10 (80.0%)
Progress: 9/10 (90.0%)
Progress: 10/10 (100.0%)
  Successful classifications: 10
  Errors: 0
  Total rows processed: 10

,snippet_id,snippet_text,entities_str,is_agent
0,CMLR1963004_S001,"On the other hand, the continental approach, p...",the court,0
1,CMLR1963005_S035,As this declaration in the cases referred to i...,"the Commission,the Commission",1
2,CMLR1963006_S028,It is particularly unrealistic of the Commissi...,"the Commission,the Commission",1
3,CMLR1963014_S009,The Council acting on a proposal olC the Com...,the Commission,0
4,CMLR1963014_S044,In cases where this Article applies the Commis...,the Commission,1
5,CMLR1963016_S028,The Council agreed to charge the Commission wi...,the Commission,1
6,CMLR1963027_S004,"This is because, throughout almost the whole p...",the Court,1
7,CMLR1963027_S039,Exchanging and agreeing medical and experts' r...,The Court,1
8,CMLR1963027_S074,It is the task of each party and not of the Co...,the Court,0
9,CMLR1963029_S009,Under the the Commission before taking any dec...,"the Commission,the Commission",1